# Generated by Django 5.1.2 on 2024-11-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True, verbose_name='Document confirmation sign'),
        ),
    ]
