# Generated by Django 5.1.2 on 2024-11-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='Specify Document Name', max_length=255, verbose_name='Document Name'),
        ),
    ]
